### ISSUE TITLE
Make sure MQTT connections are up

### ISSUE THREAD

**Issue by robertrongen** [robertrongen/smartys#37]
Potential causes:

- Publisher: Temporary failure in name resolution -> wifi temporarily disconnected?

- Subscriber: Due to Javascript browser can only use http over websockets protocol. 

Options:

- Publisher: Check settings in https://github.com/eclipse/paho.mqtt.python; Run own MQTT server?
- Subscriber: Use RabbitMQ Web MQTT Plugin (https://www.rabbitmq.com/web-mqtt.html)?

**Comment by robertrongen** [comment]
Error code pub script:
```
Traceback (most recent call last):
  File "pub-temp.py", line 30, in <module>
    mqtt_client.connect(host, port=1883, keepalive=60, bind_address="")
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by robertrongen** [comment]
Error code subscriber:
`onConnectionLost:AMQJS0008I Socket closed.`

**Comment by robertrongen** [comment]
Issue resolved by using BigClown climate module which is very stable
